/// Auto-generated by TradeVerseAI Agent
/// Purpose: Inbox Screen - Centralized notifications and direct messages hub
/// Updated to use modular components as specified in PRD

import 'package:flutter/material.dart';
import '../widgets/notification_list.dart';
import '../widgets/message_list.dart';

class InboxScreen extends StatelessWidget {
  const InboxScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ListView(
      padding: const EdgeInsets.all(16),
      children: const [
        NotificationList(),
        SizedBox(height: 16),
        MessageList(),
      ],
    );
  }
}
