/// Auto-generated by TradeVerseAI Agent
/// Purpose: Analytics Screen - Comprehensive view of performance metrics and charts
/// Updated to use modular components as specified in PRD

import 'package:flutter/material.dart';
import '../widgets/kpi_card.dart';
import '../widgets/win_loss_pie_chart.dart';
import '../widgets/trade_distribution_chart.dart';
import '../../dashboard/widgets/pnl_chart.dart';

class AnalyticsScreen extends StatelessWidget {
  const AnalyticsScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        children: [
          // KPI Cards Row
          Row(
            children: [
              Expanded(
                child: KpiCard(
                  title: 'Win Rate',
                  value: '65%',
                  icon: Icons.trending_up,
                  color: const Color(0xFF10B981),
                  trend: '+5%',
                  trendUp: true,
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: KpiCard(
                  title: 'Avg Profit',
                  value: '\$5,240',
                  icon: Icons.attach_money,
                  color: const Color(0xFF10B981),
                  subtitle: 'Monthly average',
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: KpiCard(
                  title: 'Max Drawdown',
                  value: '12%',
                  icon: Icons.trending_down,
                  color: const Color(0xFFEF4444),
                  trend: '-3%',
                  trendUp: false,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          
          // P&L Chart
          const PnLChart(),
          const SizedBox(height: 16),
          
          // Win/Loss Pie Chart
          const WinLossPieChart(
            winningTrades: 27,
            losingTrades: 15,
          ),
          const SizedBox(height: 16),
          
          // Trade Distribution Chart
          TradeDistributionChart(
            distributionData: {
              'EUR/USD': 15,
              'GBP/USD': 12,
              'USD/JPY': 8,
              'AUD/USD': 6,
              'NZD/USD': 4,
              'USD/CAD': 3,
            },
            chartType: 'instrument',
          ),
        ],
      ),
    );
  }

}
